# Generated by Django 3.2.11 on 2022-02-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_alter_contact_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
    ]
