# Generated by Django 3.2.11 on 2022-03-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Days',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
