# Generated by Django 3.2.11 on 2022-03-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_doctor_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
